stages:
  - build
  - test

include: '/ci/test/docker.yml'

build:
  stage: build
  script:
    - docker build -t $IMAGE .

test:
  stage: test
  script:
    - docker run --rm -it $IMAGE echo 'Image builded correctly'